### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by greyblake** [abesto/duolingo-to-anki#1]
I am not a scala developer.
Could you please provide some instructions of how to build the project?  And which dependencies I need? (I use Debian Linux)

**Comment by abesto** [comment]
Thanks for your interest!

The project uses `sbt`, which is (or at least was, I'm not quite up to date) the de-facto standard build system for Scala projects. I've added short instructions on how to build the project to the README. Basically all you need do is install `sbt`, then say `sbt run` or `sbt one-jar`. I've never installed `sbt` on Debian, so I'd point you to the relevant part of the `sbt` online documentation: [Installing sbt on Linux](http://www.scala-sbt.org/0.13/tutorial/Installing-sbt-on-Linux.html)

Hope this helps, let me know if you need more details.

**Comment by abesto** [comment]
Ping :)

**Comment by greyblake** [comment]
I am here!) I think it will work, thanks. I am gonna try)
