### ISSUE TITLE
Fetching is broken

### ISSUE THREAD

**Issue by vrescobar** [abesto/duolingo-to-anki#12]
500 Error at https://www.duolingo.com/vocabulary/overview

Any idea what to do? I never saw how it looks the overview page or whether is possible to obtain the vocabulary from somewhere else.

**Comment by vrescobar** [comment]
I checked again, the link is not available for eh Esperanto course.
The reason is perhaps that it is still in Beta (but not sure).

**Comment by abesto** [comment]
That definitely looks like something going wrong at Duolingo. I expect this will be fixed before Esperanto goes out of beta, but you may still want to report it to them, just in case.

Thanks for the investigation!
