### ISSUE TITLE
Can't make it run?

### ISSUE THREAD

**Issue by tonperre** [abesto/duolingo-to-anki#14]
Hi, thanks for you incredible work on that process.

I've downloaded version 0.25 and it says sth like could not find the main class net.abesto.duolingoanki 

I don't have any idea of how to run it properly ! 
By the way i installed also the other thing with gradle but can't see the way to make it run.

Thanks for your help to a newbie :)

**Comment by abesto** [comment]
Hi! Thanks for letting me know about the problem. I've just downloaded 0.25 and it works on my machine (tm), so I'm going to need some more help from you to track down what's happening.
- What operating system are you on? (Including version)
- Exactly which file did you download?
- Exactly how did you try to run it?
- What was the actual output?
- What's the output when you run `java -version`?

**Comment by tonperre** [comment]
Sorry for the late answer
- I'm on windows 7 
- I downloaded that one first : https://github.com/abesto/duolingo-to-anki and afterwards that one : https://github.com/abesto/duolingo-to-anki/releases/ (0.25)
- i ran the gradlew and after the *.jar
- The actual output is "could not find the main class: net.abesto.duolingoanki.Main Program will exit." Title of the window : Java virtual machine launcher
- java is 8 update 31 (build 1.8.0_31-b13)

Thank you for your help Abesto :)

**Comment by abesto** [comment]
Alright, that helps. I'll see if I can reproduce it.

For the record, you don't need the source, or gradlew either; the jars under https://github.com/abesto/duolingo-to-anki/releases/ are stand-alone "executables" ready for you to run.

**Comment by tonperre** [comment]
Ok good to know, first i've been given the link and followed it until
downloading the sources, but didn't get how to make it work :)

Thanks for your help man

**Comment by abesto** [comment]
Quick update, I haven't managed to reproduce the issue yet, still have a few ideas. In the meanwhile, can you please verify that the file you're using and is giving you the issues is https://github.com/abesto/duolingo-to-anki/releases/download/v0.2.5/DuolingoToAnki-0.2.5.jar ?

**Comment by abesto** [comment]
@tonperre I'm terribly sorry, I failed to reproduce your issue on the computers I have available. My guess is that I'm not asking the right questions; as a last resort, if this is still of interest, you could create a screencast from download to the error message, hopefully something on that would stand out.

**Comment by abesto** [comment]
Closing for now, please re-open if the issue persists and you have more information.
