### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zactwidale** [abesto/duolingo-to-anki#15]
I am running v0.2.5 on Windows 10 64bit with Java v8 update 101.  And your app isn't working for me.

This looks like it should be an awesome tool that Duolingo ought to incorporate natively.  But they haven't.

Unfortunately, it looks like you've lost enthusiasm for maintaining the app (which is fully understandable.)  I appreciate that there are guys like you out there making tools like this available in their own time.

Since I've seen reports of people having success with this app, I can only presume that it used to work and something has changed.

My problem is that the app generates a text file that is a log of what it has done, but is in no way remotely like an Anki flash card file.  I've attached it in case you are still trying to keep this app up to date.

[Duolingo-Spanish.txt](https://github.com/abesto/duolingo-to-anki/files/504014/Duolingo-Spanish.txt)

**Comment by zactwidale** [comment]
Disregard.... Eventually, opening the file in WordPad, rather than Notepad showed a much clearer format and I could see that the scraping log is in fact followed by the data that I was after.

I would suggest removing the log, which is not particularly helpful to the end user and only causes confusion.  Well, confused me, anyway.

Thanks for an awesome tool.

**Comment by abesto** [comment]
Hey @zactwidale, happy to see you ended up having success in the end. I'll (try to make time to) add a debug option, and print the scraping log only when it's on - should remove the confusion.

Thanks for the feedback!
