### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by code-hunger** [abesto/duolingo-to-anki#17]
I double checked my credentials, I copy pasted the same user/password in the website but I still get rejected from this program. I looked through the code in case these are not escaped properly but I didn't find anything suspicious (no experience with Scala, though).

Using the latest release on Arch linux.

**Comment by abesto** [comment]
Oh, sorry to hear that. It's been a while since I've used / updated this, Duolingo may have changed how login works on their end. I'll check this out over the weekend.

**Comment by abesto** [comment]
Just checked with my own user, login seems to work here. Please paste the application logs (either from the text-box on the UI or from STDOUT, both are the same and both are fine).

**Comment by code-hunger** [comment]
There was nothing interesting there - only the _failed login_ message. I changed temporarily my password to an alphanumeric sequence and it logged me in successfully.

In my original password there are no symbols that cannot be found on a regular qwerty keyboard with an activated Shift key, so there are no special unicode characters that could possibly create an encoding problem.

**Comment by abesto** [comment]
Encoding was a good guess. When you changed back to your original password, did you still get login failure? If you did: I'm obviously not going to ask you for your password, but I'd need to reproduce this to fix. If you could come up with a password that's _not_ one you use, but does trigger the issue, that'd be awesome.

**Comment by code-hunger** [comment]
Oh, it seems I've missed this, sorry.
It was too long ago so I'm afraid I can't provide any feedback, I've finished the deck maybe a year ago.
