### ISSUE TITLE
Program stalls after login

### ISSUE THREAD

**Issue by graham768** [abesto/duolingo-to-anki#19]
After receiving the logs
```
[2018-06-28 19:14:07.073] Trying to log in to Duolingo as <username>
[2018-06-28 19:14:07.468] Logged in to Duolingo as <username>
```
The program stalls and does not provide anymore dialog, even with the debug box checked.
Running on macOS High Sierra 10.13.4
DuolingoToAnki-0.2.6

**Comment by abesto** [comment]
Thank you for reporting this, @graham768! I've been able to reproduce the issue reliably. It seems that Duolingo has slightly changed their login method (specifically, the name of the authentication cookie has changed). https://github.com/abesto/duolingo-to-anki/releases/tag/v0.3.1 should fix the problem; please verify it works for you when you can.

**Comment by abesto** [comment]
Closing as fixed, feel free to reopen if the issue persists on your side.
