### ISSUE TITLE
Is there Anki 2.1 support?

### ISSUE THREAD

**Issue by AdrienLemaire** [abesto/duolingo-to-anki#20]
Hi @abesto,

I found your project through [this duolingo thread](https://forum.duolingo.com/comment/6889595/Easy-way-to-export-your-Duolingo-vocabulary-to-Anki-for-flashcard-review). I used duolingo a long time ago, now using Anki for the past 4 months, and while considering how to learn Esperanto, I remembered Duolingo's course was quite good, and having an adaptor to Anki like yours would be perfect for efficient learning.

But your project hasn't been updated in a year, and Anki 2.1 brought a lot of changes, so I'm not sure how effective your plugin is today. Would you have time to do update the project to latest Duolingo and Anki versions? I would be extremely grateful for that.

**Comment by abesto** [comment]
Hi @Fandekasp, thanks for the question! I just did a quick test run, and the latest release seems to be working just fine.

Feel free to open another issue if you find something's broken.

**Comment by AdrienLemaire** [comment]
Worked very well, thanks @abesto.

Maybe you can add the command to run the tool in the README (`java -jar ./DuolingoToAnki-0.3.1.jar`).

Cheers
